// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMintClubBond$Type } from "./IMintClubBond";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMintClubBond"]: IMintClubBond$Type;
    ["test/hardhat/contracts/interfaces/IMintClubBond.sol:IMintClubBond"]: IMintClubBond$Type;
  }
}
