// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { WETH9$Type } from "./WETH9";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WETH9"]: WETH9$Type;
    ["test/hardhat/contracts/mock/WETH9.sol:WETH9"]: WETH9$Type;
  }
}
