// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV1_Wrapper$Type } from "./MCV1_Wrapper";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV1_Wrapper"]: MCV1_Wrapper$Type;
    ["test/hardhat/contracts/MCV1_Wrapper.sol:MCV1_Wrapper"]: MCV1_Wrapper$Type;
  }
}
