// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Arrays$Type } from "./Arrays";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Arrays"]: Arrays$Type;
    ["@openzeppelin/contracts/utils/Arrays.sol:Arrays"]: Arrays$Type;
  }
}
