// [!region import]
import { mintclub } from 'mint.club-v2-sdk'
// [!endregion import]

// [!region rpc]
export const RPC_CHAINS: Array<RPCList> = [
  {
    id: mainnet.id,
    rpcs: [
      'https://eth.drpc.org',
      'https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7',
      'https://virginia.rpc.blxrbdn.com',
      'https://singapore.rpc.blxrbdn.com',
      'https://uk.rpc.blxrbdn.com',
      'https://rpc.ankr.com/eth',
      'https://ethereum.publicnode.com',
      'https://cloudflare-eth.com',
      'https://api.zmok.io/mainnet/oaen6dy8ff6hju9k',
      'https://eth-mainnet.public.blastapi.io',
      'https://eth.merkle.io',
      'https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://api.securerpc.com/v1',
      'https://eth.meowrpc.com',
      'https://eth.nodeconnect.org',
      'https://rpc.mevblocker.io/fullprivacy',
      'https://rpc.mevblocker.io/noreverts',
      'https://rpc.mevblocker.io',
      'https://rpc.mevblocker.io/fast',
      'https://core.gashawk.io/rpc',
      'https://rpc.payload.de',
      'https://rpc.tornadoeth.cash/eth',
      'https://rpc.tornadoeth.cash/mev',
      'https://rpc.lokibuilder.xyz/wallet',
      'https://endpoints.omniatech.io/v1/eth/mainnet/public',
    ],
  },
  {
    id: base.id,
    rpcs: ['https://base.publicnode.com', 'https://base-mainnet.public.blastapi.io', 'https://base.drpc.org'],
  },
  {
    id: optimism.id,
    rpcs: [
      'https://optimism.drpc.org',
      'https://endpoints.omniatech.io/v1/op/mainnet/public',
      'https://optimism.publicnode.com',
      'https://optimism-mainnet.public.blastapi.io',
      'https://rpc.tornadoeth.cash/optimism',
      'https://rpc.optimism.gateway.fm',
      'https://rpc.ankr.com/optimism',
      'https://1rpc.io/op',
    ],
  },
  {
    id: arbitrum.id,
    rpcs: [
      'https://arbitrum.drpc.org',
      'https://arbitrum.meowrpc.com',
      'https://arbitrum-one.public.blastapi.io',
      'https://rpc.arb1.arbitrum.gateway.fm',
      'https://arb-pokt.nodies.app',
      'https://arbitrum-one.publicnode.com',
      'https://arb1.arbitrum.io/rpc',
      'https://rpc.ankr.com/arbitrum',
      'https://endpoints.omniatech.io/v1/arbitrum/one/public',
      'https://arbitrum.blockpi.network/v1/rpc/public',
      'https://1rpc.io/arb',
      'https://arb-mainnet.g.alchemy.com/v2/654scodAkt2_QjvbCk8oPbAV6wJHoR8j',
    ],
  },
  {
    id: polygon.id,
    rpcs: [
      'https://polygon.drpc.org',
      'https://polygon.rpc.blxrbdn.com',
      'https://rpc-mainnet.matic.quiknode.pro',
      'https://polygon-bor.publicnode.com',
      'https://polygon-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://polygon-rpc.com',
      'https://rpc-mainnet.maticvigil.com',
      'https://polygon.meowrpc.com',
      'https://rpc.ankr.com/polygon',
      'https://endpoints.omniatech.io/v1/matic/mainnet/public',
      'https://rpc.tornadoeth.cash/polygon',
      'https://polygon-mainnet.public.blastapi.io',
      'https://1rpc.io/matic',
    ],
  },
  {
    id: bsc.id,
    rpcs: [
      'https://bsc-dataseed4.bnbchain.org',
      'https://bsc-dataseed2.defibit.io',
      'https://bsc-dataseed3.defibit.io',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed4.ninicoin.io',
      'https://bsc-dataseed3.bnbchain.org',
      'https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3',
      'https://binance.nodereal.io',
      'https://bsc-dataseed1.ninicoin.io',
      'https://bsc-dataseed2.ninicoin.io',
      'https://bsc-dataseed3.ninicoin.io',
      'https://bsc-dataseed1.defibit.io',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-dataseed1.bnbchain.org',
      'https://bsc.rpc.blxrbdn.com',
      'https://bsc.publicnode.com',
      'https://bsc-mainnet.public.blastapi.io',
      'https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://bsc.meowrpc.com',
      'https://rpc-bsc.48.club',
      'https://koge-rpc-bsc.48.club',
      'https://endpoints.omniatech.io/v1/bsc/mainnet/public',
      'https://bscrpc.com',
      'https://rpc.ankr.com/bsc',
      'https://rpc.tornadoeth.cash/bsc',
    ],
  },
  {
    id: avalanche.id,
    rpcs: [
      'https://avalanche.drpc.org',
      'https://rpc.tornadoeth.cash/avax',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-c-chain.publicnode.com',
      'https://avalanche.public-rpc.com',
      'https://endpoints.omniatech.io/v1/avax/mainnet/public',
      'https://api.avax.network/ext/bc/C/rpc',
    ],
  },
  {
    id: sepolia.id,
    rpcs: [
      'https://rpc.sepolia.ethpandaops.io',
      'https://eth-sepolia-public.unifra.io',
      'https://endpoints.omniatech.io/v1/eth/sepolia/public',
      'https://ethereum-sepolia.publicnode.com',
      'https://eth-sepolia.public.blastapi.io',
      'https://rpc.notadegen.com/eth/sepolia',
      'https://eth-sepolia.api.onfinality.io/public',
      'https://rpc-sepolia.rockx.com',
      'https://rpc.sepolia.org',
      'https://rpc2.sepolia.org',
      'https://sphinx.shardeum.org',
    ],
  },
]
// [!endregion rpc]
