// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MerkleDistributor$Type } from "./MerkleDistributor";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MerkleDistributor"]: MerkleDistributor$Type;
    ["test/hardhat/contracts/MerkleDistributor.sol:MerkleDistributor"]: MerkleDistributor$Type;
  }
}
