// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_Token$Type } from "./MCV2_Token";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_Token"]: MCV2_Token$Type;
    ["test/hardhat/contracts/MCV2_Token.sol:MCV2_Token"]: MCV2_Token$Type;
  }
}
