// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MerkleProof$Type } from "./MerkleProof";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MerkleProof"]: MerkleProof$Type;
    ["@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof"]: MerkleProof$Type;
  }
}
