// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TestToken$Type } from "./TestToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestToken"]: TestToken$Type;
    ["test/hardhat/contracts/mock/TestToken.sol:TestToken"]: TestToken$Type;
  }
}
