// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IBlast$Type } from "./IBlast";
import { IERC20Rebasing$Type } from "./IERC20Rebasing";
import { MCV2_BlastBond$Type } from "./MCV2_BlastBond";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBlast"]: IBlast$Type;
    ["IERC20Rebasing"]: IERC20Rebasing$Type;
    ["MCV2_BlastBond"]: MCV2_BlastBond$Type;
    ["test/hardhat/contracts/MCV2_BlastBond.sol:IBlast"]: IBlast$Type;
    ["test/hardhat/contracts/MCV2_BlastBond.sol:IERC20Rebasing"]: IERC20Rebasing$Type;
    ["test/hardhat/contracts/MCV2_BlastBond.sol:MCV2_BlastBond"]: MCV2_BlastBond$Type;
  }
}
