// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IBlast$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IBlast",
  "sourceName": "test/hardhat/contracts/MCV2_BlastBond.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "contractAddress",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        }
      ],
      "name": "claimAllGas",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "configureClaimableGas",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "contractAddress",
          "type": "address"
        }
      ],
      "name": "readClaimableYield",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IBlast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBlast$Type["abi"]>>;
  export function deployContract(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IBlast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBlast$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IBlast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBlast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IBlast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBlast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IBlast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBlast$Type["abi"]>>;
  export function getContractAt(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IBlast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBlast$Type["abi"]>>;
}
