// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IERC20Rebasing$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IERC20Rebasing",
  "sourceName": "test/hardhat/contracts/MCV2_BlastBond.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "claim",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "enum YieldMode",
          "name": "",
          "type": "uint8"
        }
      ],
      "name": "configure",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "getClaimableAmount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IERC20Rebasing",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC20Rebasing$Type["abi"]>>;
  export function deployContract(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IERC20Rebasing",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC20Rebasing$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IERC20Rebasing",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC20Rebasing$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IERC20Rebasing",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC20Rebasing$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IERC20Rebasing",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC20Rebasing$Type["abi"]>>;
  export function getContractAt(
    contractName: "test/hardhat/contracts/MCV2_BlastBond.sol:IERC20Rebasing",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC20Rebasing$Type["abi"]>>;
}
