import { Chain, FallbackTransportConfig, HttpTransportConfig, http } from 'viem';
import { arbitrum, avalanche, base, blast, bsc, cyber, mainnet, optimism, polygon, sepolia } from 'viem/chains';

export type RPCList = {
  readonly id: number;
  readonly rpcs: string[];
};

export const RPCS: Array<RPCList> = [
  {
    id: mainnet.id,
    rpcs: [
      'https://eth.drpc.org',
      'https://eth.llamarpc.com',
      'https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7',
      // 'https://virginia.rpc.blxrbdn.com',
      // 'https://singapore.rpc.blxrbdn.com',
      // 'https://uk.rpc.blxrbdn.com',
      'https://rpc.ankr.com/eth',
      // 'https://eth-pokt.nodies.app',
      // 'https://ethereum.blockpi.network/v1/rpc/public',
      'https://ethereum.publicnode.com',
      'https://cloudflare-eth.com',
      // 'https://rpc.notadegen.com/eth',
      // 'https://eth.rpc.blxrbdn.com',
      // 'https://api.zan.top/node/v1/eth/mainnet/public',
      'https://api.zmok.io/mainnet/oaen6dy8ff6hju9k',
      'https://eth-mainnet.public.blastapi.io',
      'https://eth.merkle.io',
      'https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://api.securerpc.com/v1',
      'https://eth.meowrpc.com',
      'https://eth.nodeconnect.org',
      'https://rpc.mevblocker.io/fullprivacy',
      'https://rpc.mevblocker.io/noreverts',
      'https://rpc.mevblocker.io',
      'https://rpc.mevblocker.io/fast',
      'https://core.gashawk.io/rpc',
      'https://rpc.payload.de',
      'https://rpc.tornadoeth.cash/eth',
      'https://rpc.tornadoeth.cash/mev',
      // 'https://rpc.lokibuilder.xyz/wallet',
      'https://endpoints.omniatech.io/v1/eth/mainnet/public',
      // 'https://gateway.tenderly.co/public/mainnet',
      // 'https://mainnet.gateway.tenderly.co',
      // 'https://rpc.builder0x69.io',
      // 'https://eth.api.onfinality.io/public',
      // 'https://rpc.flashbots.net/fast',
      // 'https://rpc.blocknative.com/boost',
      // 'https://api.mycryptoapi.com/eth',
      // 'https://rpc.polysplit.cloud/v1/chain/1',
      // 'https://services.tokenview.io/vipapi/nodeservice/eth?apikey=qVHq2o6jpaakcw3lRstl',
      // 'https://eth-mainnet.diamondswap.org/rpc',
      // 'https://rpc.tenderly.co/fork/c63af728-a183-4cfb-b24e-a92801463484',
      // 'https://rpc.chain49.com/ethereum?api_key=14d1a8b86d8a4b4797938332394203dc',
      // 'https://rpc.eth.gateway.fm',
      // 'https://main-light.eth.linkpool.io',
      // 'https://ethereumnodelight.app.runonflux.io',
      // 'https://mainnet.eth.cloud.ava.do',
      // 'https://eth-mainnet.g.alchemy.com/v2/demo',
      // 'https://eth-mainnet-public.unifra.io',
      // 'https://openapi.bitstack.com/v1/wNFxbiJyQsSeLrX8RRCHi7NpRxrlErZk/DjShIqLishPCTB9HiMkPHXjUM9CNM9Na/ETH/mainnet',
      // 'https://rpc.flashbots.net',
      // 'https://1rpc.io/eth',
      // 'https://go.getblock.io/d7dab8149ec04390aaa923ff2768f914',
    ],
  },
  {
    id: base.id,
    rpcs: [
      'https://base.drpc.org',
      'https://base-mainnet.public.blastapi.io',
      'https://base.publicnode.com',
      'https://base.llamarpc.com',
      // 'https://base.blockpi.network/v1/rpc/public',
      // 'https://mainnet.base.org',
      // 'https://developer-access-mainnet.base.org',
      // 'https://base-pokt.nodies.app',
      // 'https://endpoints.omniatech.io/v1/base/mainnet/public',
      // 'https://base.gateway.tenderly.co',
      // 'https://gateway.tenderly.co/public/base',
      'https://base.publicnode.com',
      'https://base-mainnet.public.blastapi.io',
      // 'https://base.api.onfinality.io/public',
      // 'https://rpc.notadegen.com/base',
      // 'https://base.meowrpc.com',
      // 'https://1rpc.io/base',
      // 'https://base-mainnet.diamondswap.org/rpc',
    ],
  },
  {
    id: optimism.id,
    rpcs: [
      'https://optimism.drpc.org',
      'https://optimism.llamarpc.com',
      // 'https://op-pokt.nodies.app',
      // 'https://api.zan.top/node/v1/opt/mainnet/public',
      'https://endpoints.omniatech.io/v1/op/mainnet/public',
      'https://optimism.publicnode.com',
      'https://optimism-mainnet.public.blastapi.io',
      'https://rpc.tornadoeth.cash/optimism',
      'https://rpc.optimism.gateway.fm',
      // 'https://mainnet.optimism.io',
      'https://rpc.ankr.com/optimism',
      // 'https://gateway.tenderly.co/public/optimism',
      // 'https://optimism.api.onfinality.io/public',
      // 'https://optimism.gateway.tenderly.co',
      // 'https://optimism.meowrpc.com',
      // 'https://optimism.blockpi.network/v1/rpc/public',
      // 'https://opt-mainnet.g.alchemy.com/v2/demo',
      'https://1rpc.io/op',
    ],
  },
  {
    id: arbitrum.id,
    rpcs: [
      'https://arbitrum.drpc.org',
      'https://arbitrum.llamarpc.com',
      // 'https://rpc.tornadoeth.cash/arbitrum',
      'https://arbitrum.meowrpc.com',
      'https://arbitrum-one.public.blastapi.io',
      'https://rpc.arb1.arbitrum.gateway.fm',
      'https://arb-pokt.nodies.app',
      // 'https://api.zan.top/node/v1/arb/one/public',
      'https://arbitrum-one.publicnode.com',
      'https://arb1.arbitrum.io/rpc',
      'https://rpc.ankr.com/arbitrum',
      'https://endpoints.omniatech.io/v1/arbitrum/one/public',
      // 'https://arb-mainnet-public.unifra.io',
      'https://arbitrum.blockpi.network/v1/rpc/public',
      // 'https://arb-mainnet.g.alchemy.com/v2/demo',
      'https://1rpc.io/arb',
    ],
  },
  {
    id: polygon.id,
    rpcs: [
      'https://polygon.drpc.org',
      'https://polygon.llamarpc.com',
      // 'https://polygon-pokt.nodies.app',
      // 'https://polygon.blockpi.network/v1/rpc/public',
      // 'https://polygon.rpc.blxrbdn.com',
      'https://rpc-mainnet.matic.quiknode.pro',
      'https://polygon-bor.publicnode.com',
      'https://polygon-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://polygon-rpc.com',
      // 'https://api.zan.top/node/v1/polygon/mainnet/public',
      'https://rpc-mainnet.maticvigil.com',
      'https://polygon.meowrpc.com',
      'https://rpc.ankr.com/polygon',
      'https://endpoints.omniatech.io/v1/matic/mainnet/public',
      'https://rpc.tornadoeth.cash/polygon',
      // 'https://polygon.api.onfinality.io/public',
      'https://polygon-mainnet.public.blastapi.io',
      // 'https://polygon.gateway.tenderly.co',
      // 'https://gateway.tenderly.co/public/polygon',
      // 'https://matic-mainnet.chainstacklabs.com',
      // 'https://getblock.io/nodes/matic',
      // 'https://polygon-mainnet.g.alchemy.com/v2/demo',
      // 'https://polygon-mainnet-public.unifra.io',
      'https://1rpc.io/matic',
      // 'https://polygonapi.terminet.io/rpc',
      // 'https://matic-mainnet-archive-rpc.bwarelabs.com',
      // 'https://matic-mainnet-full-rpc.bwarelabs.com',
      // 'https://rpc-mainnet.matic.network',
    ],
  },
  {
    id: bsc.id,
    rpcs: [
      'https://bsc-dataseed4.bnbchain.org',
      'https://binance.llamarpc.com',
      'https://bsc-dataseed2.defibit.io',
      'https://bsc-dataseed3.defibit.io',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed4.ninicoin.io',
      'https://bsc-dataseed3.bnbchain.org',
      'https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3',
      'https://binance.nodereal.io',
      'https://bsc-dataseed1.ninicoin.io',
      'https://bsc-dataseed2.ninicoin.io',
      'https://bsc-dataseed3.ninicoin.io',
      'https://bsc-dataseed1.defibit.io',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-dataseed1.bnbchain.org',
      // 'https://bsc.rpc.blxrbdn.com',
      'https://bsc.publicnode.com',
      'https://bsc-mainnet.public.blastapi.io',
      'https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://bsc.meowrpc.com',
      // 'https://bnb.api.onfinality.io/public',
      'https://rpc-bsc.48.club',
      'https://koge-rpc-bsc.48.club',
      // 'https://bsc.drpc.org',
      'https://endpoints.omniatech.io/v1/bsc/mainnet/public',
      'https://bscrpc.com',
      'https://rpc.ankr.com/bsc',
      // 'https://bsc-pokt.nodies.app',
      // 'https://api.zan.top/node/v1/bsc/mainnet/public',
      'https://rpc.tornadoeth.cash/bsc',
      // 'https://services.tokenview.io/vipapi/nodeservice/bsc?apikey=qVHq2o6jpaakcw3lRstl',
      // 'https://bsc.blockpi.network/v1/rpc/public',
      // 'https://1rpc.io/bnb',
      // 'https://nodes.vefinetwork.org/smartchain',
      // 'https://bsc-dataseed6.dict.life',
    ],
  },
  {
    id: cyber.id,
    rpcs: ['https://cyber.alt.technology/', 'https://rpc.cyber.co/'],
  },
  {
    id: avalanche.id,
    rpcs: [
      'https://avalanche.drpc.org',
      'https://rpc.tornadoeth.cash/avax',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-c-chain.publicnode.com',
      'https://avalanche.public-rpc.com',
      'https://endpoints.omniatech.io/v1/avax/mainnet/public',
      'https://api.avax.network/ext/bc/C/rpc',
      // 'https://api.zan.top/node/v1/avax/mainnet/public/ext/bc/C/rpc',
      // 'https://avax.meowrpc.com',
      // 'https://avalanche.api.onfinality.io/public/ext/bc/C/rpc',
      // 'https://avax-pokt.nodies.app/ext/bc/C/rpc',
      // 'https://avalanche.blockpi.network/v1/rpc/public',
      // 'https://1rpc.io/avax/c',
      // 'https://avalancheapi.terminet.io/ext/bc/C/rpc',
      // 'https://blastapi.io/public-api/avalanche',
    ],
  },
  {
    id: blast.id,
    rpcs: [
      // 'https://blast.din.dev/rpc',
      'https://blast.gasswap.org',
      'https://blast.blockpi.network/v1/rpc/public',
      'https://rpc.blast.io',
      'https://blastl2-mainnet.public.blastapi.io',
      'https://rpc.ankr.com/blast',
    ],
  },
  {
    id: sepolia.id,
    rpcs: [
      // 'https://gateway.tenderly.co/public/sepolia',
      // 'https://sepolia.gateway.tenderly.co',
      'https://rpc.sepolia.ethpandaops.io',
      'https://eth-sepolia-public.unifra.io',
      'https://endpoints.omniatech.io/v1/eth/sepolia/public',
      'https://ethereum-sepolia.publicnode.com',
      // 'https://ethereum-sepolia.blockpi.network/v1/rpc/public',
      'https://eth-sepolia.public.blastapi.io',
      'https://rpc.notadegen.com/eth/sepolia',
      'https://eth-sepolia.api.onfinality.io/public',
      'https://rpc-sepolia.rockx.com',
      'https://rpc.sepolia.org',
      'https://rpc2.sepolia.org',
      // 'https://sphinx.shardeum.org',
      // 'https://1rpc.io/sepolia',
      // 'https://api.zan.top/node/v1/eth/sepolia/public',
      // 'https://dapps.shardeum.org',
      // 'https://eth-sepolia.g.alchemy.com/v2/demo',
    ],
  },
];

function customTransport(params: { rpc?: string; fetchOptions?: HttpTransportConfig['fetchOptions'] }) {
  const { rpc, fetchOptions } = params;
  return http(rpc, {
    key: rpc,
    name: rpc,
    fetchOptions,
    retryCount: 0,
    timeout: 4_000,
  });
}

export function chainRPCFallbacks(
  chain: Chain,
  fetchOptions: HttpTransportConfig['fetchOptions'] = {
    cache: 'no-store',
  },
) {
  return (
    RPCS.find((c) => c.id === chain.id)?.rpcs.map((rpc) =>
      customTransport({
        rpc,
        fetchOptions,
      }),
    ) || [http()]
  );
}

export const DEFAULT_RANK_OPTIONS: FallbackTransportConfig = {
  retryCount: 0,
  rank: {
    interval: 100_000,
    sampleCount: 5,
    timeout: 4_000,
    weights: {
      latency: 0.3,
      stability: 0.7,
    },
  },
};
