// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StorageSlot$Type } from "./StorageSlot";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StorageSlot"]: StorageSlot$Type;
    ["@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot"]: StorageSlot$Type;
  }
}
