// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_Royalty$Type } from "./MCV2_Royalty";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_Royalty"]: MCV2_Royalty$Type;
    ["test/hardhat/contracts/MCV2_Royalty.sol:MCV2_Royalty"]: MCV2_Royalty$Type;
  }
}
