// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC165$Type } from "./IERC165";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC165"]: IERC165$Type;
    ["@openzeppelin/contracts/utils/introspection/IERC165.sol:IERC165"]: IERC165$Type;
  }
}
