// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Initializable$Type } from "./ERC20Initializable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Initializable"]: ERC20Initializable$Type;
    ["test/hardhat/contracts/lib/ERC20Initializable.sol:ERC20Initializable"]: ERC20Initializable$Type;
  }
}
