// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC1155Initializable$Type } from "./ERC1155Initializable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Initializable"]: ERC1155Initializable$Type;
    ["test/hardhat/contracts/lib/ERC1155Initializable.sol:ERC1155Initializable"]: ERC1155Initializable$Type;
  }
}
