// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TaxToken$Type } from "./TaxToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TaxToken"]: TaxToken$Type;
    ["test/hardhat/contracts/mock/TaxToken.sol:TaxToken"]: TaxToken$Type;
  }
}
