// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC165$Type } from "./ERC165";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC165"]: ERC165$Type;
    ["@openzeppelin/contracts/utils/introspection/ERC165.sol:ERC165"]: ERC165$Type;
  }
}
