// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_MultiToken$Type } from "./MCV2_MultiToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_MultiToken"]: MCV2_MultiToken$Type;
    ["test/hardhat/contracts/MCV2_MultiToken.sol:MCV2_MultiToken"]: MCV2_MultiToken$Type;
  }
}
