// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_Bond$Type } from "./MCV2_Bond";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_Bond"]: MCV2_Bond$Type;
    ["test/hardhat/contracts/MCV2_Bond.sol:MCV2_Bond"]: MCV2_Bond$Type;
  }
}
