// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Locker$Type } from "./Locker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Locker"]: Locker$Type;
    ["test/hardhat/contracts/Locker.sol:Locker"]: Locker$Type;
  }
}
