// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_ICommonToken$Type } from "./MCV2_ICommonToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_ICommonToken"]: MCV2_ICommonToken$Type;
    ["test/hardhat/contracts/interfaces/MCV2_ICommonToken.sol:MCV2_ICommonToken"]: MCV2_ICommonToken$Type;
  }
}
