// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MCV2_ICommonToken$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MCV2_ICommonToken",
  "sourceName": "test/hardhat/contracts/interfaces/MCV2_ICommonToken.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "burnByBond",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "mintByBond",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "name",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "symbol",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MCV2_ICommonToken",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MCV2_ICommonToken$Type["abi"]>>;
  export function deployContract(
    contractName: "test/hardhat/contracts/interfaces/MCV2_ICommonToken.sol:MCV2_ICommonToken",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MCV2_ICommonToken$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MCV2_ICommonToken",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MCV2_ICommonToken$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "test/hardhat/contracts/interfaces/MCV2_ICommonToken.sol:MCV2_ICommonToken",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MCV2_ICommonToken$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MCV2_ICommonToken",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MCV2_ICommonToken$Type["abi"]>>;
  export function getContractAt(
    contractName: "test/hardhat/contracts/interfaces/MCV2_ICommonToken.sol:MCV2_ICommonToken",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MCV2_ICommonToken$Type["abi"]>>;
}
