// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Strings$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Strings",
  "sourceName": "@openzeppelin/contracts/utils/Strings.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "StringsInsufficientHexLength",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220397d345592403b56c045bfe918bbe0efae9fb2f42d63792b63104e452b1e9d6764736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220397d345592403b56c045bfe918bbe0efae9fb2f42d63792b63104e452b1e9d6764736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
}
