// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Ownable$Type } from "./Ownable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Ownable"]: Ownable$Type;
    ["@openzeppelin/contracts/access/Ownable.sol:Ownable"]: Ownable$Type;
  }
}
