// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MCV2_ZapV1$Type } from "./MCV2_ZapV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MCV2_ZapV1"]: MCV2_ZapV1$Type;
    ["test/hardhat/contracts/MCV2_ZapV1.sol:MCV2_ZapV1"]: MCV2_ZapV1$Type;
  }
}
