// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC1155$Type } from "./ERC1155";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155"]: ERC1155$Type;
    ["@openzeppelin/contracts/token/ERC1155/ERC1155.sol:ERC1155"]: ERC1155$Type;
  }
}
