// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC1155MetadataURI$Type } from "./IERC1155MetadataURI";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1155MetadataURI"]: IERC1155MetadataURI$Type;
    ["@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol:IERC1155MetadataURI"]: IERC1155MetadataURI$Type;
  }
}
