// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC1155$Type } from "./IERC1155";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1155"]: IERC1155$Type;
    ["@openzeppelin/contracts/token/ERC1155/IERC1155.sol:IERC1155"]: IERC1155$Type;
  }
}
