// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Math$Type } from "./Math";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Math"]: Math$Type;
    ["@openzeppelin/contracts/utils/math/Math.sol:Math"]: Math$Type;
  }
}
