// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IWETH$Type } from "./IWETH";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWETH"]: IWETH$Type;
    ["test/hardhat/contracts/interfaces/IWETH.sol:IWETH"]: IWETH$Type;
  }
}
