// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TestMultiToken$Type } from "./TestMultiToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestMultiToken"]: TestMultiToken$Type;
    ["test/hardhat/contracts/mock/TestMultiToken.sol:TestMultiToken"]: TestMultiToken$Type;
  }
}
