// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Clones$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Clones",
  "sourceName": "@openzeppelin/contracts/proxy/Clones.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ERC1167FailedCreateClone",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220910ee7e0c5f7450e92e21ac6ddd4836a98cd41f7bb2db3473dd0202e528aae9f64736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220910ee7e0c5f7450e92e21ac6ddd4836a98cd41f7bb2db3473dd0202e528aae9f64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
}
